# coding: utf-8

"""
    Education Platform API

    REST API для освітньої платформи (Course, Student)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_courses_get(self) -> None:
        """Test case for courses_get

        Отримати список курсів
        """
        pass

    def test_courses_id_delete(self) -> None:
        """Test case for courses_id_delete

        Видалити курс
        """
        pass

    def test_courses_id_get(self) -> None:
        """Test case for courses_id_get

        Отримати курс за ID
        """
        pass

    def test_courses_id_put(self) -> None:
        """Test case for courses_id_put

        Оновити курс
        """
        pass

    def test_courses_post(self) -> None:
        """Test case for courses_post

        Створити новий курс
        """
        pass

    def test_students_get(self) -> None:
        """Test case for students_get

        Отримати список студентів
        """
        pass

    def test_students_id_delete(self) -> None:
        """Test case for students_id_delete

        Видалити студента
        """
        pass

    def test_students_id_get(self) -> None:
        """Test case for students_id_get

        Отримати студента за ID
        """
        pass

    def test_students_id_put(self) -> None:
        """Test case for students_id_put

        Оновити студента
        """
        pass

    def test_students_post(self) -> None:
        """Test case for students_post

        Додати студента
        """
        pass


if __name__ == '__main__':
    unittest.main()
