# coding: utf-8

# flake8: noqa
"""
    Education Platform API

    REST API для освітньої платформи (Course, Student)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.course import Course
from openapi_client.models.student import Student
